# There should be one config per bot in bots/ with the name config.<botname>.toml

[log]
# valid levels are "debug", "info", "warn", "error"
level = "info"
# valid formats are "text" and "json"
format = "text"
# whether to add the log source to the log message
add_source = true

[bot]
# ApplicationID and Token are required
application_id = 0
token = ""

# At least one guild definition is required
[guilds.guild_id]
# Wether the guild is used for the bot development
dev_guild = false
# Guild timezone
timezone = ""
# List of role IDs that the bot should have as bot roles
bot_roles = []
