// Code generated by go generate; DO NOT EDIT.
// Instead, run Makefile's "run/generator' or 'generate" targets to update this file.

package enums

import (
	"github.com/disgoorg/snowflake/v2"
)

type GuildCategoryChannelEnum string
type GuildChannelEnum string

const (
	GuildCategoryChannelQuartiersCommuns        GuildCategoryChannelEnum = "🍪 Quartiers Communs"
	GuildCategoryChannelQuartiersStrategiques   GuildCategoryChannelEnum = "🚀 Quartiers Stratégiques"
	GuildCategoryChannelQuartiersProfessionnels GuildCategoryChannelEnum = "💼 Quartiers Professionnels"
	GuildCategoryChannelQuartiersPrives         GuildCategoryChannelEnum = "🔐 Quartiers Privés"
	GuildCategoryChannelQuartiersSecurises      GuildCategoryChannelEnum = "🚨 Quartiers Sécurisés"
)

const (
	GuildChannelSasDeDecompression     GuildChannelEnum = "sas-de-décompression"
	GuildChannelReglesDuVaisseau       GuildChannelEnum = "règles-du-vaisseau"
	GuildChannelJournalDeBord          GuildChannelEnum = "journal-de-bord"
	GuildChannelCafeteria              GuildChannelEnum = "cafétéria"
	GuildChannelBureauDesPlaintes      GuildChannelEnum = "bureau-des-plaintes"
	GuildChannelHubDeDonnees           GuildChannelEnum = "hub-de-données"
	GuildChannelIntercom               GuildChannelEnum = "Intercom"
	GuildChannelDortoirs               GuildChannelEnum = "Dortoirs"
	GuildChannelPhotocopieuse          GuildChannelEnum = "photocopieuse"
	GuildChannelPantheon               GuildChannelEnum = "panthéon"
	GuildChannelPosteDePilotage        GuildChannelEnum = "Poste de pilotage"
	GuildChannelCentreDeNavigation     GuildChannelEnum = "Centre de navigation"
	GuildChannelSalleDeCommandement    GuildChannelEnum = "Salle de commandement"
	GuildChannelBattleground           GuildChannelEnum = "battleground"
	GuildChannelSalleDeReunion         GuildChannelEnum = "Salle de réunion"
	GuildChannelLesSmokeursPro         GuildChannelEnum = "les-smokeurs-pro"
	GuildChannelMurDesOuinsOuins       GuildChannelEnum = "mur-des-ouins-ouins"
	GuildChannelRegistreDeSurveillance GuildChannelEnum = "registre-de-surveillance"
	GuildChannelLaboratoire            GuildChannelEnum = "laboratoire"
	GuildChannelBureauDadministration  GuildChannelEnum = "Bureau d’administration"
	GuildChannelCapsuleDejection       GuildChannelEnum = "Capsule d’éjection"
)

var GuildCategoryChannelMap = map[GuildCategoryChannelEnum]snowflake.ID{
	GuildCategoryChannelQuartiersCommuns:        550451099166048297,
	GuildCategoryChannelQuartiersStrategiques:   927666503376076820,
	GuildCategoryChannelQuartiersProfessionnels: 802921893731762237,
	GuildCategoryChannelQuartiersPrives:         1242498003294748775,
	GuildCategoryChannelQuartiersSecurises:      1284621862193729587,
}

var GuildChannelMap = map[GuildChannelEnum]snowflake.ID{
	GuildChannelSasDeDecompression:     1285014271062970470,
	GuildChannelReglesDuVaisseau:       1284614516679905311,
	GuildChannelJournalDeBord:          1285026984606433362,
	GuildChannelCafeteria:              550451099166048298,
	GuildChannelBureauDesPlaintes:      1285332193299796028,
	GuildChannelHubDeDonnees:           1285024907868241961,
	GuildChannelIntercom:               934484018207006750,
	GuildChannelDortoirs:               1284604571662159872,
	GuildChannelPhotocopieuse:          1198271989148815484,
	GuildChannelPantheon:               1285022953481961473,
	GuildChannelPosteDePilotage:        1148629417451597885,
	GuildChannelCentreDeNavigation:     1148629459503677601,
	GuildChannelSalleDeCommandement:    927666617620500541,
	GuildChannelBattleground:           1280499340577607812,
	GuildChannelSalleDeReunion:         802922022798753793,
	GuildChannelLesSmokeursPro:         1265322648074719264,
	GuildChannelMurDesOuinsOuins:       1286418129714548939,
	GuildChannelRegistreDeSurveillance: 1284998508897767555,
	GuildChannelLaboratoire:            1286850367488790581,
	GuildChannelBureauDadministration:  1285346159346319472,
	GuildChannelCapsuleDejection:       1284622169350864956,
}

var GuildChannelCategoryMap = map[GuildChannelEnum]snowflake.ID{
	GuildChannelSasDeDecompression:     0,
	GuildChannelReglesDuVaisseau:       0,
	GuildChannelJournalDeBord:          0,
	GuildChannelCafeteria:              550451099166048297,
	GuildChannelBureauDesPlaintes:      550451099166048297,
	GuildChannelHubDeDonnees:           550451099166048297,
	GuildChannelIntercom:               550451099166048297,
	GuildChannelDortoirs:               550451099166048297,
	GuildChannelPhotocopieuse:          927666503376076820,
	GuildChannelPantheon:               927666503376076820,
	GuildChannelPosteDePilotage:        927666503376076820,
	GuildChannelCentreDeNavigation:     927666503376076820,
	GuildChannelSalleDeCommandement:    927666503376076820,
	GuildChannelBattleground:           802921893731762237,
	GuildChannelSalleDeReunion:         802921893731762237,
	GuildChannelLesSmokeursPro:         1242498003294748775,
	GuildChannelMurDesOuinsOuins:       1242498003294748775,
	GuildChannelRegistreDeSurveillance: 1284621862193729587,
	GuildChannelLaboratoire:            1284621862193729587,
	GuildChannelBureauDadministration:  1284621862193729587,
	GuildChannelCapsuleDejection:       1284621862193729587,
}

// Guild Category Channels functions

func (e GuildCategoryChannelEnum) String() string {
	return string(e)
}

func (e GuildCategoryChannelEnum) ID() snowflake.ID {
	return GuildCategoryChannelMap[e]
}

func (e GuildCategoryChannelEnum) IsValid() bool {
	_, ok := GuildCategoryChannelMap[e]
	return ok
}

func (e GuildCategoryChannelEnum) GetChannels() []GuildChannelEnum {
	var channels []GuildChannelEnum
	for channel, parentID := range GuildChannelCategoryMap {
		if parentID == e.ID() {
			channels = append(channels, channel)
		}
	}
	return channels
}

// Guild Channels functions

func (e GuildChannelEnum) String() string {
	return string(e)
}

func (e GuildChannelEnum) ID() snowflake.ID {
	return GuildChannelMap[e]
}

func (e GuildChannelEnum) IsValid() bool {
	_, ok := GuildChannelMap[e]
	return ok
}

func (e GuildChannelEnum) ParentID() snowflake.ID {
	return GuildChannelCategoryMap[e]
}
