// Code generated by go generate; DO NOT EDIT.
// Instead, run Makefile's "run/generator' or 'generate" targets to update this file.

package enums

import (
	"github.com/disgoorg/snowflake/v2"
)

type RoleEnum string

const (
	RoleCapitaine                RoleEnum = "Capitaine"
	RoleIntelligenceArtificielle RoleEnum = "Intelligence Artificielle"
	RoleQuinn                    RoleEnum = "Quinn"
	RoleAdjointDuCapitaine       RoleEnum = "Adjoint du Capitaine"
	RoleGardienDesCookies        RoleEnum = "Gardien des Cookies"
	RoleMembreDequipage          RoleEnum = "Membre d’équipage"
	RoleRecrue                   RoleEnum = "Recrue"
	RoleExplorateur              RoleEnum = "Explorateur"
	RoleIngenieur                RoleEnum = "Ingénieur"
	RolePrisonnierDuMepris       RoleEnum = "Prisonnier du Mépris"
	RoleFilsDInvictus            RoleEnum = "Fils d’Invictus"
	RoleEveryone                 RoleEnum = "@everyone"
)

var RoleMap = map[RoleEnum]snowflake.ID{
	RoleCapitaine:                1284597292459888824,
	RoleIntelligenceArtificielle: 1286850619801604148,
	RoleQuinn:                    1285051433699508368,
	RoleAdjointDuCapitaine:       1284597706706128906,
	RoleGardienDesCookies:        1248347987353272503,
	RoleMembreDequipage:          1284597855931203756,
	RoleRecrue:                   1284598017839595632,
	RoleExplorateur:              1285350867331190825,
	RoleIngenieur:                1285351118515339274,
	RolePrisonnierDuMepris:       1285374094673580042,
	RoleFilsDInvictus:            1284909117399502918,
	RoleEveryone:                 550451098658275358,
}

func (e RoleEnum) String() string {
	return string(e)
}

func (e RoleEnum) ID() snowflake.ID {
	return RoleMap[e]
}

func (e RoleEnum) IsValid() bool {
	_, ok := RoleMap[e]
	return ok
}
